### PR TITLE
Add release notes for 22.12

### PR DESCRIPTION
**Pull request by the-mikedavis**

### CODE REVIEW

**Comment by pickfire** [comment]
Should we have netlify or some sort of stuff that let us preview the new release notes? It doesn't seem easy to just review the casts from github.

**Comment by pickfire** [comment]
I requested access on netlify for helix-editor/website, maybe later I can try set it up.

**Comment by archseer** [comment]
Can we re-record the gifs? They're easily 2MB+

**Comment by the-mikedavis** [comment]
Ah yeah I was worried about that. Recording gifs with wf-recorder as mp4 and then converting to gif with ffmpeg always makes them horribly blurry so I tried to bump up the quality and now they're huge 😅. I'll see if I can re-record and reduce the size

**Comment by archseer** [comment]
Are they not doable as an asciinema recording? I guess because of the underlines? Probably enough to just provide a screenshot there

**Comment by archseer** [comment]
Let's also link to https://www.youtube.com/watch?v=xHebvTGOdH8 (probably best introductory video I've seen so far), https://www.youtube.com/watch?v=8L308PdmhMY

There's also https://www.youtube.com/watch?v=Un_vn8U4cEw

**Comment by the-mikedavis** [comment]
Yeah the asciinema player and/or recorder doesn't seem to support extended underlines. Maybe the auto-save one is doable as an asciicast if we can find a multiplexer that sends focus events. I tried tmux but that didn't work out of the box (though maybe it just needs some configuration)

**Comment by gabydd** [comment]
I wonder if https://github.com/tamasfe/taplo/pull/354 should be mentioned somewhere so there isn't a flood of issues/matrix questions about the editor hanging when 2022.12 is released

**Comment by the-mikedavis** [comment]
I don't think that's a very large snag, we can handle that separately if it becomes common in the issue tracker

**Review by archseer — APPROVED** [review]

**Pull request merged**
