### PR TITLE
Use code editor instead of text editor

### PR DESCRIPTION
**Pull request by yashpalgoyal1304**
Destination link: 
https://helix-editor.com

Reasoning:
* helix is not _just_ a text editor;
* it's much _much_ more than that, it's a code editor through and through, and proudly so
* the code editing out of the box _is_ what separates helix from other modal editors

the helix website basically screams code editing (slight exaggeration, but u get the idea 😅)
4 out of 6 "selling points" mentioned on helix site apply _only_ on code editing:
* ... which allow concurrent _code editing._
* Tree-sitter integrations ... _code navigation_
* Code manipulation ... [on] syntax tree nodes _instead of plain text_
* Language server support

### CODE REVIEW

**Comment by archseer** [comment]
A code editor is a sub-category of a text editor.

**Comment by yashpalgoyal1304** [comment]
> A code editor is a sub-category of a text editor.

I was thinking same while posting this. But:

- Code editor is a sub-category of a text editor in the sense that "every code editor is a text editor but not vice versa"
- Text editor is a sub-category of code editor in the sense that "code editor contains all of text editing features but not vice versa"

So, in this particular case, i think that it should be pretty obvious to anyone that code editor is capable of text editing as well.

**Comment by the-mikedavis** [comment]
For the large editor projects: the entire lineage ed->ex->vi->vim, neovim ("hyperextensible Vim-based text editor" https://neovim.io), emacs, Sublite Text and Atom (plus the [xray](https://github.com/atom-archive/xray) subproject) all say that they're text editors. Zed, Kakoune and [pepper](https://github.com/vamolessa/pepper) are notable ones that call themselves "code editors" but among the other medium/small-sized editor projects, these are all text editors that have builtin code utilities: [micro](https://github.com/zyedidia/micro), [Xi](https://github.com/xi-editor/xi-editor), [lite](https://github.com/rxi/lite), [slap](https://github.com/slap-editor/slap), [amp](https://github.com/jmacdonald/amp), [zee](https://github.com/zee-editor/zee), [iota](https://github.com/gchp/iota), [ved](https://github.com/vlang/ved), [led](https://github.com/cessen/led). Some use the terms interchangeably like [Ox](https://github.com/curlpipe/ox).

Text editor is the historic term AFAIK for any project that edits text and code. Editors for only text and not code are plain-text editors.

> Text editor is a sub-category of code editor in the sense that "code editor contains text editing features but not necessarily vice versa"

No: code editing features are a superset of text editing features and that implies that code editors are a subset of text editors, not the other way around.

I also disagree with the argument that since code editing features are built-in then it's a code editor. For one angle: it's possible to build and use Helix without code editing features like tree-sitter and not use LSP (there's also a PR to be able to disable LSP). And for another: Kakoune calls itself a code editor even though syntax tree and LSP features are not built-in and can only be accomplished by plugin.

**Comment by yashpalgoyal1304** [comment]
> No: code editing features are a superset of text editing features and that implies that code editors are a subset of text editors, not the other way around.

ohkay, yeah, i couldn't resolve this confusion of terms regarding superset of features, but subset otherwise. Thanks for correcting me and clearing it up.

> Editors for only text and not code are plain-text editors.

well, that's _almost_ a fair point too.

> it's possible to build and use Helix without code editing features like tree-sitter and not use LSP

umh, yeah, but that choice of disabling is like an added feature. it's different than the _inability_ to have the needed things without requiring significant effort.

> Kakoune calls itself a code editor even though syntax tree and LSP features are not built-in and can only be accomplished by plugin

is that plugin available by default?? if yes, then i'd say it's still qualified. Same goes for VS Code. It has those things available as plugins - but those are built-in available.

> the other medium/small-sized editor projects, these are all text editors that have builtin code utilities

umh, yeah, following code-specific editing features are supported by lots of editors, but these are mostly it, nothing more:
* syntax highlighting,
* toggling single/multi-line comments
* code folding

----

**Comment by yashpalgoyal1304** [comment]
But 
- helix goes to great lengths (by default) for code editing
- ... which combined with its great-vim-like text editing grammar features (match, change, swap/[rotate selection], etc.); 
- ... provides a code editing capability which i have never seen before, 

[rotate selection]: https://github.com/helix-editor/helix/discussions/3981

and i genuinely feel it should be given credit for it in the noun it uses. hence the suggestion.

**Comment by yashpalgoyal1304** [comment]
made sense: ST7vnfKjfvY
sory, i was wrong

**Pull request closed without merging**
