### PR TITLE
feat: style adjustements, logo, etc.

### PR DESCRIPTION
**Pull request by matoous**
Experimental commit that introduces Helix logo,
adjusts styles a bit, adds call to action in the nav,
etc.

The logo is just for showcase, this will have to wait until the final version is decided.

- add download button to the top navigation
- add logo to the Helix in top navigation
- add logo as a fav icon
- replace `Inter` font with system font stack (I don't think there's large difference and we don't have to load custom font, but this is an opinionated change)

I am also wondering, maybe it would be nice to have small gifs showcasing individual features on the main page?

### CODE REVIEW

**Comment by matoous** [comment]
Screen Shot 2022-04-27 at 20 03 31

**Comment by archseer** [comment]
Hmm, I quite like `Inter` and I was intending to use it on the webgpu frontend as the UI font. I'd keep it but replace Google Fonts with a copy of the variable font to reduce size: https://rsms.me/inter/#variable

**Comment by archseer** [comment]
I'd also keep the two tone look (white buttons) and the slight color halo (background gradient) to add some depth

**Comment by matoous** [comment]
Sorry, no time for this now. Rather than keeping it hanging I am closing it. Will try to take a look once I find more time to contribute.

**Pull request closed without merging**
